#!/usr/bin/env bash
# Mechanical shortcut-pattern sweep — deterministic input to the review stage. Generated by /spec:init.
# Usage: [DIFF_BASE=<ref>] scripts/spec-patterns.sh [dir ...]    (defaults to src)
# Pure report: always exits 0. Sanctioned exceptions exist — the reviewer judges; this only counts.
set -u
DIRS=("$@")
[ ${#DIRS[@]} -eq 0 ] && DIRS=(src)
echo "## Mechanical pattern sweep"; echo "Scope: ${DIRS[*]}"; echo
sweep() {
  local name="$1"; shift
  local out; out=$(rg -n "$@" "${DIRS[@]}" 2>/dev/null || true)
  local count=0
  [ -n "$out" ] && count=$(printf '%s\n' "$out" | wc -l | tr -d ' ')
  echo "### ${name}: ${count}"
  if [ -n "$out" ]; then
    printf '%s\n' "$out" | head -15 | sed 's/^/    /'
    [ "$count" -gt 15 ] && echo "    ... (${count} total)"
  fi
  echo
}
sweep "as any" -e ':\s*any\b|as any' -g '!*.test.ts' -g '!*.test.tsx'
sweep "non-null assertion" -e '[A-Za-z0-9_)\]]!\.' -g 'src/**'
sweep "host alias import inside the package" -e "from ['\"]@/" -g 'src/**'
sweep "console.log on a JSON path" -e 'console\.log' -g 'src/cli/**'
echo "Sweep complete. Counts are leads, not verdicts — sanctioned exceptions exist."
exit 0
